name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      skip_testpypi:
        description: skip uploading to TestPyPI
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'

permissions:
  contents: read

jobs:
  testpypi-publish:
    if: github.event.inputs.skip_testpypi == 'no'
    name: upload release to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish --repository testpypi

  pypi-publish:
    needs: testpypi-publish
    if: always() && !failure()
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish

  install:
    needs: pypi-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: install from PyPI
      run: |
        python -m pip install --upgrade pip
        python -m pip install commensurability
