name: tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:
    inputs:
      coveralls:
        type: boolean
        description: upload coverage report to coveralls
        default: false


jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: pdm sync
      run: |
        pdm sync -G dev, -G github
    - name: tox
      run: |
        pdm run -v tox
    - name: coverage
      run: |
        pdm run -v coverage xml
    - uses: coverallsapp/github-action@v2
      with:
        flag-name: run-${{ matrix.os }}-${{ matrix.python-version }}
        format: cobertura
        parallel: true

  coveralls:
    needs: tox
    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && inputs.coveralls)
    runs-on: ubuntu-latest
    steps:
    - name: coveralls
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "run-windows-latest-3.11,run-windows-latest-3.12,run-ubuntu-latest-3.11,run-ubuntu-latest-3.12,run-macos-latest-3.11,run-macos-latest-3.12"
